// Generated by CoffeeScript 1.6.3
(function() {
  var bin, path, shell;

  shell = require('shelljs');

  path = require('path');

  bin = 'node ' + path.resolve(path.join(__dirname, '..', 'bin', 'phonegap.js'));

  describe('$ phonegap [options] commands', function() {
    beforeEach(function() {
      return spyOn(process.stdout, 'write');
    });
    it('should support no arguments', function() {
      var process;
      process = shell.exec(bin + '', {
        silent: true
      });
      return expect(process.output).toMatch('Usage:');
    });
    it('should support commands', function() {
      var process;
      process = shell.exec(bin + ' version', {
        silent: true
      });
      return expect(process.output).toMatch(/^\w+\.\w+\.\w+/);
    });
    return it('should support options', function() {
      var process;
      process = shell.exec(bin + ' --version', {
        silent: true
      });
      return expect(process.output).toMatch(/^\w+\.\w+\.\w+/);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=cli.spec.map
*/
