// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      coffee: {
        compile: {
          expand: true,
          cwd: './',
          src: ['bin/**/*.coffee', 'lib/**/*.coffee'],
          dest: './',
          ext: '.js'
        }
      },
      watch: {
        app: {
          files: '**/*.coffee',
          tasks: ['coffee:compile']
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.registerTask('build', ['coffee:compile']);
    return grunt.registerTask('default', ['build']);
  };

}).call(this);

/*
//@ sourceMappingURL=Gruntfile.map
*/
